### ISSUE TITLE
Radon, flake8, and pyflakes seem to be working with pycodestyle 2.5.0

### ISSUE THREAD

**Issue by CartoonFan** [cemsbr/yala#136]
Hey there! I saw that radon and pyflakes were removed to support pycodestyle >= 2.4.0. I tried both tools with pycodestyle 2.5.0 and both seemed to work correctly, so maybe it's a good time to bring them back? Thanks for all your hard work!

**Comment by cemsbr** [comment]
Thank you for the news. I've started working on this and radon is back to yala since version 1.8.0.

**Comment by CartoonFan** [comment]
You're welcome. Thank you for the update! :smiley:

**Comment by cemsbr** [comment]
Just added flake8 and pyflakes to 2.0.0. Please, check the README about changes on how to install dependencies. For the v1 behavior, use `pip install yala[all]`.
